# Docker Compose file for local deployments

version: "3.8"

services:
  # Configuration for the Apache container running the Q2A site
  php-apache-environment:
    container_name: q2a-apache              # Custom name for the q2a Apache server
    build:                                  # Build a new image
      context: ./                           # Source of the container
      dockerfile: Dockerfile                # Dockerfile to build from
    image: q2a-php-apache-local             # Name of the image of the Apache server being created
    restart: on-failure                     # Restart this container if a failure occurs
    depends_on:                             # Ensure this container starts *after* the DB container is running
      - "db"                                # Must be the name of the database *container*
    environment:                            # these vars must be the same as in q2a-config.php^
      DB_HOST: 'q2a-db'
      DB_PORT: '3306' # most likely 3306
      DB_LOGIN: 'user'
      DB_KEY: 'password'
      DB_NAME: 'qadb-local'
    volumes:                                # Bind the source directory to the website container
      - type: bind                          # Bind instead of Volume because we want to be able to make changes to the source folder without re-composing the container
        source: ./public                         # Must be the directory containing `index.php`
        target: /var/www/html/              # Default root for Apache web server
      - type: bind                          # This bind mount allows the web server to access config information
        source: ./config                    #   without the website having direct access to those files
        target: /var/www/config/            #
    ports:                                  # Define what ports should be open for traffic
      - "8080:80"                           # Open 80 on the host to allow HTTP traffic
      - "8443:443"                          # Open 443 on the host to allow HTTPS traffic

  # Configuration for the Q2A database container
  db:
    container_name: q2a-db                  # Note that this is used for the `QA_MYSQL_HOSTNAME` env var in `qa-config-external.php` in the Q2A container
    image: mysql:latest                     # Using a mySQL database
    restart: always                         # Always restart the container. See `https://www.cloudbees.com/blog/ensuring-containers-are-always-running-with-dockers-restart-policy` for more restart policies
    command:
      # need to remove the STRICT_TRANS_TABLES sql_mode, the rest are to enable the other defaults. ref https://dev.mysql.com/doc/refman/9.2/en/sql-mode.html
      - --sql_mode=ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    environment:                            # Setting the mySQL environment variables
      # This var is not used in `qa-config-external.php`
      MYSQL_ROOT_PASSWORD: root
      # Name of the *database*, not the container
      MYSQL_DATABASE: qadb-local
      # Username used in `qa-config-secure.php`
      MYSQL_USER: user
      # Password used in `qa-config-secure.php`
      MYSQL_PASSWORD: password
    ports:                                  # This allows us to access the MySQL database remotely (Remove after ETL)
      - "9906:3306"                         # 3306 is default for SQL
    volumes:                                # Volume for data persistence
      - type: volume                        # Use a Volume over a Bind to make managing data easier
        source: q2a_db_volume               # This volume is located on the HOST MACHINE
        target: /var/lib/mysql              # Location of the MySQL database

  mailer:
    container_name: q2a-mailer
    build:
      context: ./mailer
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:                            # these vars must be the same as in q2a-config.php^
      DB_HOST: q2a-db
      DB_PORT: 3306 # most likely 3306
      DB_LOGIN: user
      DB_KEY: password
      DB_NAME: qadb-local

      SMTP_HOST: smtppro.zoho.com
      SMTP_PORT: 587
      SMTP_USER: dev@support.bible
      SMTP_PASSWORD: Nur=JilnowbUsDiamed0
      SMTP_TO_EMAIL: bob_beck@sil.org
    restart: on-failure
    
volumes:                                    # These volumes are stored on /var/lib/docker/volumes/ (on Linux)
  q2a_db_volume:                            # Persistent storage for DB
