apiVersion: batch/v1
kind: Job
metadata:
  name: sb-mysql
  labels:
    app: support-bible
    tier: db
spec:
  template:
    spec:
      containers:
      - name: support-bible-mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rootpwd
              name: mysql-secret
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database
              name: mysql-secret
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: mysql-secret
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-secret
        ports:
        - containerPort: 3306
          name: mysql
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: v1
kind: Service
metadata:
  name: sb-mysql
  labels:
    app: support-bible
    tier: db
spec:
  type: ExternalName
  externalName: replaceWithRDSName
  ports:
    - port: 3306
  selector:
    app: support-bible
    tier: db

