apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-mysql
  labels:
    app: support-bible
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-bible
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: support-bible
        tier: db
    spec:
      containers:
      - image: mysql
        name: support-bible-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rootpwd
              name: mysql-secret
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database
              name: mysql-secret
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: mysql-secret
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-secret
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: sb-mysql
  labels:
    app: support-bible
    tier: db
spec:
  ports:
    - port: 3306
  selector:
    app: support-bible
    tier: db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: support-bible
    tier: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

