apiVersion: v1
kind: Service
metadata:
  name: q2a-mysql
  labels:
    app: q2a
spec:
  ports:
    - port: 3306
  selector:
    app: q2a
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: q2a
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: q2a-mysql
  labels:
    app: q2a
spec:
  selector:
    matchLabels:
      app: q2a
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: q2a
        tier: mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
          - name: MYSQL_DATABASE
            value: q2a-mysql-db
          - name: MYSQL_PASSWORD
            value: #password in config
          - name: MYSQL_ROOT_PASSWORD
            value: #enter your root password
          - name: MYSQL_USER
            value: #username in config
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
