apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-mysql
  labels:
    app: support-bible
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-bible
      tier: db
  template:
    metadata:
      labels:
        app: support-bible
        tier: db
    spec:
      containers:
      - name: support-bible-mysql
        image: mysql
        env:
        - name: MYSQL_HOST
          valueFrom: 
            secretKeyRef:
              key: dbhost
              name: mysql-secret
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rootpwd
              name: mysql-secret
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database
              name: mysql-secret
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: mysql-secret
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-secret
        ports:
        - containerPort: 3306
          name: mysql
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sb-mysql
  labels:
    app: support-bible
    tier: db
spec:
  type: ClusterIP
  ports:
    - port: 3306
      name: mysql
      targetPort: mysql
  selector:
    app: support-bible
    tier: db

