name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: release-please
        id: release
        uses: googleapis/release-please-action@a6d1fd9854c8c40688a72f7e4b072a1e965860a0 # v4.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
